name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  DEBIAN_FRONTEND: noninteractive
  HOMEBREW_NO_AUTO_UPDATE: 1
  PAWPAW_VERSION: 8c69660ab10b75cd7a488f41386dbcb4c8802c5a

jobs:
  # macOS native intel build
  macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ~/PawPawBuilds/builds
          ~/PawPawBuilds/downloads
          ~/PawPawBuilds/targets
        key: macos
    - name: Set up dependencies
      run: |
        brew install cmake jq meson
    - name: Bootstrap macOS intel
      shell: bash
      run: |
        if [ ! -d PawPaw ]; then
          git clone https://github.com/DISTRHO/PawPaw.git
          git -C PawPaw checkout ${PAWPAW_VERSION}
        fi
        ./PawPaw/bootstrap-jack2.sh macos && ./PawPaw/.cleanup.sh macos
    - name: Build jack2
      shell: bash
      run: |
        pushd PawPaw && source local.env macos && popd
        python ./waf configure --platform=darwin --prefix=/usr/local
        python ./waf build -j $(sysctl -n hw.logicalcpu)
        python ./waf install --destdir=$(pwd)/destdir
    - name: Set sha8
      id: slug
      run: echo "::set-output name=sha8::$(echo ${{ github.sha }} | cut -c1-8)"
    - name: Generate macOS package
      shell: bash
      run: |
        ./macosx/generate-pkg.sh $(pwd)/destdir/usr/local ${{ github.event.pull_request.number || steps.slug.outputs.sha8 }}
        ls ./macosx
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: jack2-macOS-intel
        path: macosx/jack2-osx-*.pkg
